spring:
  shardingsphere:

    defaultDataSourceName: mysql-0

    datasource:
      # 配置真实数据源
      names: mysql-0

      # 配置第 1 个数据源
      mysql-0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:6896/testsharding
        username: zhang
        password: 9H0pVn7d

    mode:
      # 内存模式
      type: Memory

    props:
      # 打印SQl
      sql-show: true

    rules:
      sharding:
        tables:
          business_info:
            actual-data-nodes: mysql-0.business_info_$->{0..4}
            # 分表策略
            table-strategy:
              standard:
                # 分片算法名称
                sharding-algorithm-name: alg_hash_mod
                # 分片列名称
                sharding-column: customerId


        # 分片算法配置
        sharding-algorithms:
          # 行表达式分片算法
          alg_inline_userid:
            props:
              # 分片算法属性配置
              algorithm-expression: server-order$->{user_id % 2}
            # 分片算法类型
            type: INLINE
          alg_mod:
            props:
              # 分片算法属性配置
              sharding-count: 2
            # 取模分片算法
            type: MOD
          alg_hash_mod:
            props:
              # 分片算法属性配置
              sharding-count: 4
            # 分片算法类型
            type: HASH_MOD
        key-generators:
          # 分布式序列算法配置
          alg_snowflake:
            # 分布式序列算法类型
            type: SNOWFLAKE
            # 分布式序列算法属性配置
          #            props:
        # 绑定表
        #        binding-tables:
        #          - t_order,t_order_item
        # 广播表
#        broadcast-tables:
#          - t_dict

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false


abcd:
  ef: aabcde
  cd: ac3eg